#!/usr/bin/env Rscript
suppressPackageStartupMessages(library(data.table))
a <- commandArgs(trailingOnly=TRUE)
i <- match('--workspace',a)
if(is.na(i)||i==length(a)) stop('Usage: Rscript audit_coloc_catalogue_v54.R --workspace PATH',call.=FALSE)
root <- normalizePath(a[[i+1L]],winslash='/',mustWork=TRUE)
base <- file.path(root,'results','module12','colocalization')
read <- function(...) {p<-file.path(base,...);if(!file.exists(p)) stop('Missing: ',p,call.=FALSE);fread(p,showProgress=FALSE)}
q <- read('work_queue','module12_1_coloc_work_queue_eligible.tsv.gz')
s <- read('catalogue','status','module12_3_unit_status.tsv')
c <- read('catalogue','summary','module12_3_coloc_catalogue_summary.tsv.gz')
x <- read('catalogue','summary','module12_3_coloc_catalogue_qc.tsv.gz')
need <- function(d,cols,label) {m<-setdiff(cols,names(d));if(length(m)) stop(label,' missing: ',paste(m,collapse=', '),call.=FALSE)}
need(q,'coloc_unit_id','queue');need(s,c('coloc_unit_id','catalogue_status'),'status')
need(c,c('coloc_unit_id','PP.H0','PP.H1','PP.H2','PP.H3','PP.H4','posterior_sum'),'summary')
need(x,c('coloc_unit_id','critical_failures','final_status'),'QC')
ids <- as.character(q$coloc_unit_id)
uniq <- function(d) uniqueN(d$coloc_unit_id)
missing_s <- setdiff(ids,s$coloc_unit_id)
missing_c <- setdiff(ids,c$coloc_unit_id)
missing_x <- setdiff(ids,x$coloc_unit_id)
extra_s <- setdiff(s$coloc_unit_id,ids)
extra_c <- setdiff(c$coloc_unit_id,ids)
extra_x <- setdiff(x$coloc_unit_id,ids)
pp <- as.matrix(c[,lapply(.SD,as.numeric),.SDcols=paste0('PP.H',0:4)])
ps <- suppressWarnings(as.numeric(c$posterior_sum))
posterior_bad <- sum(!is.finite(ps)|abs(ps-1)>1e-6|!is.finite(rowSums(pp))|abs(rowSums(pp)-1)>1e-6|rowSums(!is.finite(pp))>0|rowSums(pp<0|pp>1,na.rm=TRUE)>0)
crit <- suppressWarnings(as.numeric(x$critical_failures))
status_counts <- s[,.N,by=catalogue_status][order(catalogue_status)]
qc_counts <- x[,.N,by=final_status][order(final_status)]
audit <- data.table(metric=c('eligible_queue_rows','status_rows','summary_rows','qc_rows','unique_queue_ids','unique_status_ids','unique_summary_ids','unique_qc_ids','missing_status_ids','missing_summary_ids','missing_qc_ids','extra_status_ids','extra_summary_ids','extra_qc_ids','failed_unit_status','bad_unit_status','nonzero_or_missing_critical_qc','invalid_posteriors'),value=c(nrow(q),nrow(s),nrow(c),nrow(x),uniq(q),uniq(s),uniq(c),uniq(x),length(missing_s),length(missing_c),length(missing_x),length(extra_s),length(extra_c),length(extra_x),sum(s$catalogue_status=='FAIL',na.rm=TRUE),sum(is.na(s$catalogue_status)|!s$catalogue_status%in%c('PASS','PASS_WITH_WARNINGS')),sum(is.na(crit)|crit!=0),posterior_bad))
out <- file.path(base,'catalogue','audit_v54');dir.create(out,recursive=TRUE,showWarnings=FALSE)
fwrite(audit,file.path(out,'audit.tsv'),sep='\t');fwrite(status_counts,file.path(out,'unit_status_counts.tsv'),sep='\t');fwrite(qc_counts,file.path(out,'qc_status_counts.tsv'),sep='\t')
cat('Unit statuses:\n');print(status_counts)
cat('QC statuses:\n');print(qc_counts)
cat('Catalogue audit:\n');print(audit)
pass <- nrow(q)==9814L && all(audit$value[2:8]==9814L) && all(audit$value[9:nrow(audit)]==0L)
cat('Result: ',if(pass)'PASS' else 'FAIL','\nAudit: ',file.path(out,'audit.tsv'),'\n',sep='')
if(!pass) quit(save='no',status=1L)
