#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly=TRUE)
i <- match('--workspace',args)
if (is.na(i)||i==length(args)) stop('Usage: Rscript lock_environment_v72.R --workspace PATH',call.=FALSE)
root <- normalizePath(args[[i+1L]],winslash='/',mustWork=TRUE)
if (!requireNamespace('renv',quietly=TRUE)) stop('Install renv to the R 4.6.0 library first: install.packages("renv"); rerun this script.',call.=FALSE)
if (getRversion()!=package_version('4.6.0')) stop('Expected R 4.6.0; observed ',getRversion(),call.=FALSE)
base <- c(data.table='1.18.4',coloc='5.2.3',susieR='0.14.2',arrow='24.0.0',dplyr='1.2.1',ggplot2='4.0.3',patchwork='1.3.2',scales='1.4.0',ggalluvial='0.12.6',ggrepel='0.9.8',forcats='1.0.1',openxlsx='4.2.8.1')
actual <- vapply(names(base),function(n) if(requireNamespace(n,quietly=TRUE)) as.character(utils::packageVersion(n)) else NA_character_,character(1))
if(anyNA(actual)||any(actual!=base))stop('Package versions differ: ',paste(names(base)[is.na(actual)|actual!=base],collapse=', '),call.=FALSE)
out<-file.path(root,'results','release_audit_v72');dir.create(out,recursive=TRUE,showWarnings=FALSE)
lock<-file.path(out,'renv.lock')
if(file.exists(lock))stop('Lockfile already exists; inspect before replacing: ',lock,call.=FALSE)
renv::snapshot(project=root,library=.libPaths(),lockfile=lock,packages=names(base),prompt=FALSE)
if(!file.exists(lock)||file.info(lock)$size<=0)stop('Lockfile missing or empty',call.=FALSE)
cat('PASS environment snapshot: ',lock,'\n',sep='')
cat('Record renv version: ',as.character(utils::packageVersion('renv')),'\n',sep='')
