#!/usr/bin/env Rscript
suppressPackageStartupMessages(library(data.table))
a<-commandArgs(trailingOnly=TRUE);i<-match('--workspace',a)
if(is.na(i)||i==length(a))stop('Usage: Rscript validate_clean_release_v71.R --workspace PATH',call.=FALSE)
root<-normalizePath(a[[i+1L]],winslash='/',mustWork=TRUE)
out<-file.path(root,'results','release_audit_v71');dir.create(out,recursive=TRUE,showWarnings=FALSE)
read<-function(p){f<-file.path(root,p);if(!file.exists(f))stop('Missing required output: ',f,call.=FALSE);fread(f,showProgress=FALSE)}
check<-function(metric,observed,expected){data.table(metric,observed=as.character(observed),expected=as.character(expected),result=if(length(observed)==1L&&!is.na(observed)&&identical(as.character(observed),as.character(expected)))'PASS' else 'FAIL')}
checks<-list()
add<-function(metric,observed,expected){checks[[length(checks)+1L]]<<-check(metric,observed,expected)}
phase<-read('results/GCST90691600_QC_summary.tsv')
add('GWAS clean variants',phase$n_clean_rows[[1L]],21831407)
q<-read('results/module12/colocalization/work_queue/module12_1_coloc_work_queue_eligible.tsv.gz')
u<-read('results/module12/colocalization/catalogue/status/module12_3_unit_status.tsv')
s<-read('results/module12/colocalization/catalogue/summary/module12_3_coloc_catalogue_summary.tsv.gz')
qc<-read('results/module12/colocalization/catalogue/summary/module12_3_coloc_catalogue_qc.tsv.gz')
for(n in c('eligible','unit status','catalogue','catalogue QC')) add(paste(n,'rows'),nrow(switch(n,eligible=q,'unit status'=u,catalogue=s,'catalogue QC'=qc)),9814)
for(n in c('eligible','unit status','catalogue','catalogue QC'))add(paste(n,'unique IDs'),uniqueN(switch(n,eligible=q,'unit status'=u,catalogue=s,'catalogue QC'=qc)$coloc_unit_id),9814)
add('queue equals catalogue IDs',setequal(q$coloc_unit_id,s$coloc_unit_id),TRUE)
add('queue equals status IDs',setequal(q$coloc_unit_id,u$coloc_unit_id),TRUE)
add('queue equals QC IDs',setequal(q$coloc_unit_id,qc$coloc_unit_id),TRUE)
add('failed units',sum(u$catalogue_status=='FAIL',na.rm=TRUE),0)
add('critical unit QC',sum(as.integer(qc$critical_failures),na.rm=TRUE),0)
add('invalid posteriors',sum(is.na(s$posterior_sum)|abs(s$posterior_sum-1)>1e-6),0)
module11<-read('results/module11/harmonization/catalogue/module11_3B_4_final_qc_status.tsv')
add('Module 11 final QC',module11$final_status[[1L]],'PASS')
priority<-read('results/module12/colocalization/prioritization/module12_4_status.tsv')
reclass<-read('results/module12/reclassification/module12_6_status.tsv')
add('Module 12.4',priority$final_status[[1L]],'PASS')
add('Module 12.6',reclass$status[[1L]],'SUCCESS')
for(n in c('input_coloc_units','strong_h4_units','moderate_h4_units','suggestive_h4_units','h3_dominant_units'))add(paste('priority',n),priority[[n]][[1L]],c(input_coloc_units=9814,strong_h4_units=30,moderate_h4_units=54,suggestive_h4_units=239,h3_dominant_units=424)[[n]])
for(n in c('total_clumps','evaluable_clumps','reclassified_clumps'))add(paste('reclass',n),reclass[[n]][[1L]],c(total_clumps=1325,evaluable_clumps=130,reclassified_clumps=111)[[n]])
fig_checks<-read('results/release_figure_audit_v70/checks.tsv')
fig_files<-read('results/release_figure_audit_v70/figure_manifest.tsv')
add('figure numeric checks PASS',sum(fig_checks$status=='PASS'),23)
add('figure files PASS',sum(fig_files$status=='PASS'),33)
reconciliation<-read('results/module12/reconciliation_v59/audit.tsv')
for(n in c('old_rows','new_rows','shared_keys','old_only','new_only','shared_posterior_changed'))add(paste('reconciliation',n),reconciliation[metric==n,value][[1L]],c(old_rows=9471,new_rows=9814,shared_keys=7609,old_only=1862,new_only=2205,shared_posterior_changed=0)[[n]])
inputs<-data.table(relative_path=c('data/gwas/GCST90691600.h.tsv','data/annotations/gencode/gencode.v50.primary_assembly.annotation.gtf.gz','reference/1000G_GRCh38/1000G_GRCh38_EUR_uniqueID.pgen','reference/1000G_GRCh38/1000G_GRCh38_EUR_uniqueID.pvar.zst','reference/1000G_GRCh38/1000G_GRCh38_EUR_uniqueID.psam','data/expression/GTEx/Skin_Sun_Exposed_Lower_leg.v10.eQTLs.signif_pairs.parquet','data/expression/GTEx/Skin_Not_Sun_Exposed_Suprapubic.v10.eQTLs.signif_pairs.parquet'))
inputs[,path:=file.path(root,relative_path)];inputs[,bytes:=file.info(path)$size];inputs[,present:=!is.na(bytes)&bytes>0]
add('required inputs present',sum(inputs$present),nrow(inputs))
parquet<-list.files(file.path(root,'data','GTEx_v10_apaQTL'),pattern='[.]parquet$',full.names=TRUE)
add('apaQTL Parquet inputs',length(parquet),46)
pkgs<-c('data.table','coloc','susieR','arrow','dplyr','ggplot2','patchwork','scales','ggalluvial','ggrepel','forcats','openxlsx')
versions<-data.table(package=pkgs,version=vapply(pkgs,function(x)if(requireNamespace(x,quietly=TRUE))as.character(packageVersion(x))else NA_character_,character(1)))
add('required packages installed',sum(!is.na(versions$version)),length(pkgs))
audit<-rbindlist(checks)
fwrite(audit,file.path(out,'audit.tsv'),sep='\t');fwrite(inputs,file.path(out,'inputs.tsv'),sep='\t');fwrite(versions,file.path(out,'R_package_versions.tsv'),sep='\t')
writeLines(capture.output(sessionInfo()),file.path(out,'sessionInfo.txt'))
cat('Validation checks: ',sum(audit$result=='PASS'),'/',nrow(audit),'\n',sep='')
if(any(audit$result!='PASS'))print(audit[result!='PASS'])
cat('Result: ',if(all(audit$result=='PASS'))'PASS' else 'FAIL','\nAudit: ',out,'\n',sep='')
if(any(audit$result!='PASS'))quit(save='no',status=1L)
